project:
  type: website
  resources:
    - bib/*_bib.html
    - downloads

website:
  title: "Andrew M. Raim"
  site-url: "https://andrewraim.github.io"
  navbar:
    right:
      - href: posts.qmd
        text: Posts
      - href: publications.qmd
        text: Publications
      - href: presentations.qmd
        text: Presentations
      - href: software.qmd
        text: Software
      - href: resources.qmd
        text: Resources
  search: false
  page-footer: 
    left:
      - icon: mailbox
        text: "andrew dot raim at gmail dot com"
    right: "Views expressed on this site are solely those of the author." 

format:
  html:
    theme:
      - default
      - styles.css
    toc: false
    linestretch: 1.2
    fontsize: 12pt
    mainfont: arial

