Much of the software listed here is free and open source with major
contributions from - or developed entirely by - dedicated community members. I
am grateful for the vast selection of reliable, high quality, and
readily-available software that has been developed under this philopsophy.

# The R Project

- [R](https://www.r-project.org) The R Project for Statistical Computing.

- [CRAN](https://cran.r-project.org) A major repository of contributed R
  packages.

- [Rstudio](https://posit.co) An integrated development environment (IDE) for
  R users. An open source project maintained by the Posit company.

- [sf](https://cran.r-project.org/package=sf) A comprehesive package for
  working with shapefiles and other geographic objects.

- [tidyverse](https://www.tidyverse.org) Packages for data wrangling,
  plotting, and other fundamental data science tasks.

- [pbdR](https://pbdr.org) Packages for high-performance computing.

- [Rcpp](https://www.rcpp.org) Framework for integrating C++ into R.

- [R-Nimble](https://r-nimble.org) Framework for constructing hierarchical
  models with compiled code for high performance.

- [LaplacesDemon](https://github.com/LaplacesDemonR/LaplacesDemon)
  Full-featured library for Bayesian computation.

# Platforms for Statistical and Scientific Computing

- [Stan](https://mc-stan.org) Declare Bayesian models and compile into fast
  executable programs that sample posterior by Hamiltonian Monte Carlo;
  integrates with R and some other general purpose languages.

- [OpenBUGS](https://www.mrc-bsu.cam.ac.uk/software/bugs/openbugs) Linux
  variant of WinBUGS, one of the first (as far as I know) Bayesian modeling
  platforms that automate MCMC based on a user's model specification.

- [The Julia Language](https://julialang.org)
  A high-level and high-performance language for technical computing.

- [GNU Octave](https://octave.org) A scientific computing platform that is
  largely compatible with
  [MATLAB](https://www.mathworks.com/products/matlab.html), but is open source.

- [Wolfram Alpha](https://www.wolframalpha.com) Search engine that can compute
  integrals, limits, etc.

- [Python](https://www.python.org) High-level language for data science and
  general computing.

# Libraries

- [GSL](https://www.gnu.org/software/gsl) The GNU Scientific Library.
  Implements a number of numerical methods including integration,
  optimization, and root-finding.A

- [Netlib](https://www.netlib.org) A repository of code and documentation for
  numerical methods. A good place to find definitions of standard FORTRAN codes
  for standards such as BLAS and LAPACK.

- [Armadillo](https://arma.sourceforge.net) A matrix algebra library for C++.
  Accessible to Rcpp users through the package
  [RcppArmadillo](https://cran.r-project.org/package=RcppArmadillo).

- [Eigen](https://eigen.tuxfamily.org) Another matrix algebra library for C++.
  It is also available to Rcpp users through the package
  [RcppEigen](https://cran.r-project.org/package=RcppEigen).
  I find this one more difficult to use than Armadillo. 

- [STL](https://cplusplus.com/reference/) The C++ Standard Template Library
  provides a number of data structures, iterators, and algorithms for working
  in C++.

- [Boost](https://www.boost.org) Provides a suite of data structures,
  iterators, and algorithms like the STL. However, the STL is typically
  installed on machines with C++ compilers while Boost seems to be less
  standard.

# Documentation Tools

- [Latex](https://www.latex-project.org) System for preparing high quality
  documents. Especially useful for typsetting mathematical expressions.

- [beamer](https://ctan.org/pkg/beamer) Package for making slides with Latex.

- [UMBCposter](https://www.math.umbc.edu/~rouben/umbcposter) A Latex package
  for making posters. Developed and maintained by Dr. Rouben Rostamian at UMBC.

- [beamerposter](https://ctan.org/pkg/beamerposter) Another Latex package for
  making conference posters.

- [TeXstudio](https://www.texstudio.org) IDE for authoring Latex documents.

- [pgf](https://ctan.org/pkg/pgf) Latex package for technical graphics. Also
  see [pgfplots](https://ctan.org/pkg/pgfplots).

- [Quarto](https://quarto.org) Framework to generate articles, websites,
  books, and other documents with markdown and embedded R, Python, or Julia
  code.

# Collaboration

- [Git](https://git-scm.com) Tool for source control management. Especially
  suitable for text-oriented material such as source code.

- [Codeberg](https://codeberg.org/) a free hosting service for Git projects
  which is maintained by a non-profit organization in Berlin.

- [Bitbucket](https://bitbucket.org),
  [Github](https://github.com),
  [GitLab](https://gitlab.com)
  Paid services that host Git projects.
  They each have a free tier with limited hosting of private projects and use
  of [large file storage](https://git-lfs.com), but are a good option for
  enlisting collaborators who do not otherwise have an account.

- [Overleaf](https://www.overleaf.com) Collaboration environment for writing
  Latex documents. Provides a browser-based editor, and also supports Git to
  work outside of the editor.

- [Box](https://www.box.com),
  [DropBox](https://www.dropbox.com),
  [Google Drive](https://drive.google.com)
  Shared storage, for files other than source code

# Productivity Tools

- [Ubuntu](https://ubuntu.com) A distribution of Linux maintained by
  the Canonical company. A number of variants are available such as a server
  edition and desktop editions with various window managers.

- [Arch Linux](https://archlinux.org) A distribution of Linux that follows a
  rolling release model. Good for keeping up with the most recent versions of
  packages. Also good for customization because the initial installation is
  minimal.

- [Linux](https://www.linux.org) The kernel for Linux distributions. Started
  as a personal project by Linus Torvalds and became a collaboration with
  contributors from around the world.

- [Cygwin](https://www.cygwin.com) A collection of open source tools that
  provides a Linux-like experience in Windows, especially through the command
  line.

- [Virtual Machine Manager](https://virt-manager.org) An application to run and
  manage virtual machines. Uses the [libvirt](https://libvirt.org/)
  virtualization API. Both of these are open source.

- [Firefox](https://www.mozilla.org/en-US/firefox) A popular open source web
  browser.

- [Chromium](https://www.chromium.org) The open source web browser on which
  [Google Chrome](https://www.google.com/chrome/) is built.

- [OBS Studio](https://obsproject.com) Capture your PC's display, audio, and
  video for recording or streaming.

- [Audacity](https://www.audacityteam.org) Audio recording, editing, and
  processing.

- [Flowblade](https://jliljebl.github.io/flowblade) Video editing.

- [GIMP](https://www.gimp.org) Image editing.

- [VLC](https://www.videolan.org/vlc) a media player for audio and video.

- [dwm](https://dwm.suckless.org) Extremely lightweight and minimalist tiling
  window manager for X11. Also see [dwl](https://codeberg.org/dwl) for
  Wayland.

- [dmenu](https://tools.suckless.org/dmenu) A lightweight X11 menu system
  which can be leveraged to create user defined menus. Menus can be traversed
  with the keyboard through fuzzy search. Something similar can be accomplished
  on the command line with [fzf](https://github.com/junegunn/fzf).

- [tmux](https://github.com/tmux/tmux/wiki) Persistent terminal sessions that
  can be detached/attached and split into multiple panes. Here is a
  [cheat sheet](https://gist.github.com/MohamedAlaa/2961058) with some useful
  commands and keybindings.

- [screen](https://www.gnu.org/software/screen) An alternative to tmux; also
  provides persistent terminal sessions.

- [Vim](https://www.vim.org) Well-estabished text editor that can be used in
  non-graphical terminal environments. Tedious edits can often be accomplished
  with a small number of commands or keystrokes. A
  [cheat sheet](https://vim.rtorr.com) can be helpful to keep nearby.

- [Emacs](https://www.gnu.org/software/emacs) An alternative to Vim which has
  a different feel.

- [Nano](https://www.nano-editor.org) A user-friendly text editor for the
  terminal. Recommended over Vim and Emacs for new terminal users.

- [Bash](https://www.gnu.org/software/bash) One of the standard shells for
  Linux-based systems. Supports scripting which can be used to automate tedious
  tasks.

- [Mutt](http://www.mutt.org) A well-established email client for the terminal.
  Also see [NeoMutt](https://neomutt.org) which is a fork of Mutt that supports
  some additional features.

- [Alpine](https://alpineapp.email) The successor of
  [Pine](https://web.archive.org/web/20190328145000/http://www.washington.edu/pine)
  which was another widely used email client for the terminal.

- [Slurm](https://slurm.schedmd.com) A scheduler to queue up computing jobs
  and run them as processors become available. Useful for running large
  simulations which can require hours or days. Most commonly used on multi-user
  systems and distributed computing clusters, but also useful on a PC.

- [Xournalpp](https://xournalpp.github.io) Take handwritten notes on your
  computer which can be edited and maintained as files. Especially useful with
  a writing tablet such as the
  [Wacom Intuous](https://www.wacom.com/en-us/products/pen-tablets/wacom-intuos).

- [Write](https://www.styluslabs.com) Another excellent program for handwritten
  notes by Stylus Labs. Appears to be free but not completely open source like
  Xournal.

- [Dia](https://wiki.gnome.org/Apps/Dia) Open source tool for drawing diagrams.

- [The GNU Project](https://www.gnu.org) hosts a number of open source software
  projects, including the [gcc](https://www.gnu.org/software/gcc) compiler,
  [make](https://www.gnu.org/software/make) and
  [autoconf](https://www.gnu.org/software/autoconf/) build tools, as well as
  some of the other tools listed on the present page.

# Professional Associations

- [American Statistical Association](https://www.amstat.org)

- [Institute of Mathematical Statistics](https://imstat.org)

- [Statistical Society of Canada](https://www.ssc.ca)

# U.S. Census Bureau

- [Center for Statistical Research and Methodology](https://www.census.gov/topics/research/stat-research.html)
  Information about the center and technical reports.

- [Census Data Explorer](https://data.census.gov) Explore and download data
  from the decennial census, American Community Survey, and other public data
  releases.

- [TIGER/Line Shapefiles](https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.html)
  Shapefiles for states, counties, and other geographic entities in the United
  States. Useful for plotting and spatial statistics.

- [2020 Census Data Products](https://www.census.gov/programs-surveys/decennial-census/decade/2020/planning-management/release/about-2020-data-products.html)
  Description of data products from the 2020 Decennial Census which make use of
  new methods to protect confidentiality. The release status for each product
  is given here.

# University of Maryland, Baltimore County

- [Department of Mathematics and Statistics](https://mathstat.umbc.edu)

- [Department of Computer Science and Electrical Engineering](https://www.csee.umbc.edu)

- [High Performance Computing Facility](https://www.umbc.edu/hpcf)

- [REU Site: Interdisciplinary Program in High Performance Computing](https://www.umbc.edu/hpcreu)

- [Center for Interdisciplinary Consulting](https://www.umbc.edu/circ)

# Nostaglia

- [M-Net](https://www.arbornet.org/m-net.php) One of the first public-access
  UNIX systems. Hosted by the Arbornet organization in Ann Arbor, Michigan.

- [GeoCities](https://thehistoryoftheweb.com/an-ode-to-geocities) Provided free
  hosting for personal websites.

- [Gopher](https://mncomputinghistory.com/gopher-protocol) An early protocol
  for browsing the web through a system of terminal-based menus. It lost
  traction as graphical HTTP-based browsers such as
  [NCSA Mosiac](https://www.ncsa.illinois.edu/research/project-highlights/ncsa-mosaic)
  became widely used.

