# R packages

- `allocation`: Exact optimal allocation algorithms for stratified sampling.
  [[cran](https://cran.r-project.org/package=allocation) |
  [repo](https://github.com/andrewraim/allocation)
  ]

- `COMMultReg`: Conway-Maxwell multinomial regression.
  [[repo](https://github.com/andrewraim/COMMultReg)]

- `COMPoissonReg`: Conway-Maxwell Poisson regression.
  [[cran](https://cran.r-project.org/package=COMPoissonReg) |
  [repo](https://github.com/lotze/COMPoissonReg)
  ]

- `DirectSampling`: Direct sampling with a step function. Also see
  [DirectSampling.jl](https://github.com/andrewraim/DirectSampling.jl) for
  a Julia implementation.
  [[repo](https://github.com/andrewraim/DirectSampling)
  ]

- `fntl`: Numerical Tools for Rcpp and Lambda Functions.
  [[cran](https://cran.r-project.org/package=fntl) |
  [repo](https://github.com/andrewraim/fntl)
  ]

- `ldr`: Methods for likelihood-based dimension reduction in regression.
  [[cran](https://cran.r-project.org/package=ldr) |
  [repo](https://bitbucket.org/umbc_sdr/ldr)
  ]

- `ManifoldOptim`: An R interface to the [ROPTLIB][roptlib] library for
  Riemannian manifold optimization.
  [[cran](https://cran.r-project.org/package=ManifoldOptim) |
  [repo](https://bitbucket.org/umbc_sdr/ManifoldOptim)
  ]

- `mixlink`: Mixture link regression.
  [[cran](https://cran.r-project.org/package=mixlink) |
  [repo](https://github.com/andrewraim/mixlink)
  ]

- `OverdispersionModelsInR`: Some tools to help with MLE computation,
  especially for non-standard likelihoods found in overdispersion models.
  [[repo](https://github.com/andrewraim/OverdispersionModelsInR)
  ]

- `raim`: a collection of my utility functions.
  [[repo](https://github.com/andrewraim/raim)
  ]

- `sfreader`: Read summary files with census data. Currently focused on the
  2010 SF2 summary file.
  [[repo](https://github.com/andrewraim/sfreader)
  ]
 
- `stcos`: Space-time change of support.
  [[cran](https://cran.r-project.org/package=stcos) |
  [repo](https://github.com/holans/ST-COS)
  ]

- `vws`: Vertical Weighted Strips in R using C++.
  [[cran](https://cran.r-project.org/package=vws) |
  [repo](https://github.com/andrewraim/vws)
  ]

[roptlib]: https://www.math.fsu.edu/~whuang2/Indices/index_ROPTLIB.html

# Templates for Documents

- `beamerthemeraim`: A custom Beamer theme. Provides a small info bar at the
  bottom but is otherwise minimal.
  [[repo](https://github.com/andrewraim/beamerthemeraim)
  ]

- `formula-sheet`: Formula sheets in Latex.
  [[www](software/formula-sheet.qmd)
  ]

- `latex-business-card`: Business cards in Latex.
  [[www](software/latex-business-card.qmd)
  ]

- `latex-resume`: CV / resume in Latex.
  [[www](software/latex-resume.qmd)
  ]

- `quarto-templates`:  Documents such as an article, slides, and a vignette in
  Quarto.
  [[repo](https://github.com/andrewraim/quarto-templates)
  ]

- `sweave-templates`: Slides and articles using Sweave via knitr.
  [[repo](https://github.com/andrewraim/sweave-templates)
  ]

# Utilities


- `bashrc`: my Bash configuration and customizations.
  [[repo](https://github.com/andrewraim/bashrc)
  ]

- `panfig`: a command line utility to facilitate compiling files with pandoc.
  Group commonly used Pandoc options into configuration entries that can be
  easily invoked by an alias (e.g., "slides").
  [[repo](https://github.com/andrewraim/panfig)
  ]

- `vimrc`: my Vim configuration and customizations.
  [[repo](https://github.com/andrewraim/vimrc)
  ]

- `worker`: a tool to help run repetitive computational studies such as
  statistical simulations. Run several workers at a time for simple parallel
  computing.
  [[repo](https://github.com/andrewraim/worker)
  ]

