---
title: LaTeX Business Card
---

There are a few nice tutorials on the web on how to make a business card
in LaTeX. I started from
[this one](http://blog.widmann.org.uk/2009/05/27/1297)
and transformed it to a UMBC theme. I didn't design this UMBC theme myself;
I used a standard UMBC business card that I received, and tried to emulate it
as closely as possible.

Note that UMBC people can get their cards printed out at
[Commonvision](http://commonvision.umbc.edu)
and that students get a discount.

Here is an [example](/downloads/latex-business-card/example.pdf) that uses the
template. To generate it, download the following files and place them together
in the same directory.

* [offsetred.pdf](/downloads/latex-business-card/offsetred.pdf) a UMBC logo
  (from [here](http://www.umbc.edu/umbcstyle/wordmarks.html)),
  converted to PDF format.
* [example.tex](/downloads/latex-business-card/example.tex) latex for example.

To generate the PDF on a standard Linux setup:

```bash
$ pdflatex example.tex
```

As usual, you may need to repeat the `pdflatex` command several times to
resolve references in the document. This should yield the PDF file
`example.pdf` You should also be able to compile the example with your favorite
LaTeX IDE.

