---
title: "Rejection Sampling with Vertical Weighted Strips"
date: 2024-01-19
categories:
  - article
bibliography: ../bib/web.bib
draft: true
---

Rejection sampling is a classical algorithm [@vonNeumann1951] to generate
variates from a target distribution that may not otherwise have a well-known
construction method---e.g., by composing other random variables. A benefit of
rejection sampling is that accepted draws follow the target distribution
exactly. However, coming up with a good proposal for rejection sampling can
take some creativity while a poor choice can result in extremely low acceptance
rates where practically no draws can be accepted from a very large number of
candidates.

@VWS2024 explore an approach to construct proposals by regarding the target as
a weighted density and majorizing the weight function. This yields another
weighted density whose unnormalized form can be used as an envelope in the
acceptance ratio. If designed purposefully, the normalized form can also be
used to draw candidate variates to complete the rejection sampler.  An improved
proposal can be obtained by partitioning the support and majorizing within each
region; this results in a finite mixture.  The method is referred to as
"vertical weighted strips" because it can be regarded as an extension of the
vertical strips method [@Devroye1986, Section 3.6; @MartinoLuengoMiguez2018,
Chapter VIII], with the weighted form introducing an additional degree of
flexibility for algorithm development.

